### ISSUE TITLE
Doc request: specifying dbt version

### ISSUE THREAD

**Issue by rubenvereecken** [meltano/dbt-ext#51]
What’s the recommended way to get a newer version of dbt? I managed in the end, but it was far from obvious, and I feel like there are more obvious ways to do it.

Steps:
1. `meltano add utility dbt-bigquery --no-install` -> this adds the following to `meltano.yml` without installing the old versions of dbt
```yaml
  utilities:
  - name: dbt-bigquery
    variant: dbt-labs
    pip_url: dbt-core~=1.5.4 dbt-bigquery~=1.5.4 git+https://github.com/meltano/dbt-ext.git@main
```
2. Change the versions to `1.7.2`
3. Run `meltano install`

If this _is_ the best way to get the latest supported version of dbt, I suggest we add this to the docs. Happy to help if you point me in the right direction.
